[package]
name = "superflake"
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"
description = "Ultra-safe identification technology"
authors = ["Foundry Industries", "Aidak <hello@aidak.dev>"]

[dependencies]
